steps:
- name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
  args:
  - gcloud
  - functions
  - deploy
  - getdetails
  - --region=us-west1
  - --source=./getdetails/
  - --trigger-http
  - --runtime=python39